### ISSUE TITLE
Change in plugin installation process

### ISSUE THREAD

**Issue by blueraaga** [philippfromme/camunda-modeler-plugin-resize-tasks#2]
Hi @philippfromme ,

First, thanks for the plugin. Really appreciate the effort! 🥇 

I just noted that the plugin installation process has changed. More info [here](https://github.com/camunda/camunda-modeler/tree/master/docs/plugins).

This happened after your installation process didn't work for me.

Hope it would hake sense to you. Let me know if I misinterpreted something.

**Comment by philippfromme** [comment]
What exactly doesn't work?

**Comment by blueraaga** [comment]
I hope you looked into the link.

Environment: I am using Windows 10 Pro / Camunda Modeler 3.5.0.

Based on the instruction in README.md, I had put the downloaded folder (I downloaded the  ZIP as I didn't want to do the build myself) in the recommended location `%APPDATA%/camunda-modeler` but after restarting the application, the resizing feature was not working.

So I googled and then follow the instruction in the link in my previous comment and then the plugin worked as expected (I could resize). Therefore, I think the installation instruction might need an update.

**Comment by philippfromme** [comment]
I think the documentation is not clear enough. After downloading and extracting the plugin you can copy it to `%APPDATA%/camunda-modeler/resources/plugins/camunda-modeler-plugin-resize-tasks` so it will be available in all versions of the Camunda Modeler that you download. Note that after extracting the plugin that you downloaded from GitHub it will be nested inside the extracted directory. It will look something like this: `C:\Users\philipp\Downloads\camunda-modeler-plugin-resize-tasks-master\camunda-modeler-plugin-resize-tasks-master`. The Camunda Modeler will __not__ recognize plugins inside nested directories. Therefore, you need to copy the directory that's inside the extracted directory to the `%APPDATA%/camunda-modeler/resources/plugins`.

I will improve the documentation.

**Comment by philippfromme** [comment]
@blueraaga I've tried to improve the documentation about where to put plugins. If you're interested, check out: https://github.com/camunda/camunda-modeler/tree/master/docs/search-paths

**Comment by blueraaga** [comment]
Thanks again @philippfromme! Great work with this plugin! I am closing the issue.
